name: BuildContainerImage

on:
  push:
    branches:
      - 'v0.13-kse'
  # Keep it only for test purpose, comment it once everything is ok
  workflow_dispatch:

env:
  # TODO: Change variable to your image's repo.
  IMAGE_REPO: ${{ vars.IMAGE_REPO }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Declare some variables
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
          echo "suffix=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          # echo "suffix=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.IMAGE_REPO }}/vcluster:${{ env.branch }}-${{ env.suffix }}
